# Generated by Django 3.0.8 on 2020-07-29 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200729_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 19, 4, 36, 797307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 19, 4, 36, 797307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 19, 4, 36, 795313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 19, 4, 36, 795313, tzinfo=utc)),
        ),
    ]
