# Generated by Django 3.0.8 on 2020-07-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200730_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow_time',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='date_updated',
        ),
    ]
